image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

services:
  - docker:dind

stages:
  - build
  - tests
  - quality-assurance

variables:
  APP_PATH: ./app/symfony
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  COMPOSE_FILE: "docker-compose.yml:docker-compose.gitlab-ci.yml"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $APP_PATH/public/build
    - $APP_PATH/node_modules
    - $APP_PATH/vendor

.gitlab-container-registry: &internal-image
  before_script:
    - apk add --no-cache make
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker-compose pull http php node || true
  tags:
    - docker

## Stage build
build-docker:
  <<: *internal-image
  stage: build
  script:
    - make build
    - make start
    - make symfony:.env.local
    - make symfony:vendor
    - make symfony:node_modules
    - make symfony:assets
    - docker-compose push

## Stage tests
phpunit:
  <<: *internal-image
  stage: tests
  script:
    - make start
    - make symfony:phpunit

behat:
  <<: *internal-image
  stage: tests
  script:
    - make start
    - make symfony:db-init
    - make symfony:behat

## Stage quality-assurance
security:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:security

lint:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:lint

php-cs-fixer:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:qa_php-cs-fixer

phpcs:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:phpcbf
    - make symfony:phpcs

phploc:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:phploc

phpcpd:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:phpcpd

phpmd:
  <<: *internal-image
  stage: quality-assurance
  script:
    - make start
    - make symfony:phpmd
